kind: pipeline
name: default

steps:
- name: build
  image: ruby:2.7
  pull: true
  commands:
  - gem install bundler
  - bundle install
  - JEKYLL_ENV=production bundle exec jekyll build
- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [ "rick.kerjean.me" ]
    source: _site/*
    target: /mnt/me-kerjean-pages/projects/filestash/website
    recursive: true
    delete: true
    user:
      from_secret: RSYNC_USER
    key:
      from_secret: RSYNC_KEY
